"""reconcile_schema_with_models

Revision ID: 42ac53c9be5c
Revises: 0010_expand_ingredient_amount
Create Date: 2026-07-15 22:07:48.595411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql

revision: str = '42ac53c9be5c'
down_revision: Union[str, None] = '0010_expand_ingredient_amount'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping a whole MySQL table also drops its indexes and foreign keys.
    # Checking existence makes this safe to resume after interrupted DDL.
    existing_tables = set(inspect(op.get_bind()).get_table_names())
    for table_name in (
        'ceramic_materials',
        'user_daily_views',
        'purchases',
        'body_materials',
        'material_oxide_backup_20260714_oxide_fill',
    ):
        if table_name in existing_tables:
            op.drop_table(table_name)
    op.create_foreign_key('fk_favorites_user_id', 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('firing_curves', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='所属用户，null=系统默认',
               existing_nullable=True)
    op.drop_index('idx_user_id', table_name='firing_curves')
    op.create_index(op.f('ix_firing_curves_user_id'), 'firing_curves', ['user_id'], unique=False)
    op.create_foreign_key('fk_firing_curves_user_id', 'firing_curves', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ingredient_names_id'), 'ingredient_names', ['id'], unique=False)
    op.alter_column('material_substitutions', 'source_material_id',
               existing_type=mysql.INTEGER(),
               comment='源材料',
               existing_nullable=False)
    op.alter_column('material_substitutions', 'target_material_id',
               existing_type=mysql.INTEGER(),
               comment='相似材料',
               existing_nullable=False)
    op.alter_column('material_substitutions', 'similarity_score',
               existing_type=mysql.FLOAT(),
               comment='成分相似度 0-100',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('material_substitutions', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='历史兼容字段，不再参与业务逻辑',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('material_substitutions', 'note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='相似关系备注',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.create_index(op.f('ix_material_substitutions_id'), 'material_substitutions', ['id'], unique=False)
    op.alter_column('materials', 'name_en',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('materials', 'source',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_index('idx_materials_name', table_name='materials')
    op.drop_index('idx_materials_name_en', table_name='materials')
    op.drop_index('idx_materials_source', table_name='materials')
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.drop_index('idx_user_time', table_name='notifications')
    op.drop_index('idx_user_unread', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key('fk_notifications_user_id', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_notifications_from_user_id', 'notifications', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_notifications_work_id', 'notifications', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recipe_ingredients', 'is_additional',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('idx_name_hash', table_name='recipe_ingredients')
    op.drop_index('idx_recipe_id', table_name='recipe_ingredients')
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_name_hash'), 'recipe_ingredients', ['name_hash'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_foreign_key('fk_recipe_ingredients_recipe_id', 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_recipe_seger_recipe_id', table_name='recipe_seger')
    op.create_index(op.f('ix_recipe_seger_id'), 'recipe_seger', ['id'], unique=False)
    op.alter_column('recipe_sequences', 'digits',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'3'"))
    op.create_index(op.f('ix_recipe_versions_id'), 'recipe_versions', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.drop_index('idx_recipe_id', table_name='recipe_versions')
    op.create_foreign_key('fk_recipe_versions_created_by', 'recipe_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('recipes', 'cover',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='封面',
               existing_nullable=True)
    op.alter_column('recipes', 'images',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='图片',
               existing_nullable=True)
    op.alter_column('recipes', 'describe',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('recipes', 'category',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('recipes', 'temperature',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='温度',
               existing_nullable=True)
    op.alter_column('recipes', 'atmosphere',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='气氛',
               existing_nullable=True)
    op.alter_column('recipes', 'kiln_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='窑炉类型',
               existing_nullable=True)
    op.alter_column('recipes', 'body_material',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='坯体料',
               existing_nullable=True)
    op.alter_column('recipes', 'visibility',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='可见性',
               existing_nullable=True)
    op.alter_column('recipes', 'likes',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True)
    op.alter_column('recipes', 'work_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='作品数量',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('recipes', 'forked_from',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='二改来源配方',
               existing_nullable=True)
    op.alter_column('recipes', 'source',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='来源',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'source_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='来源ID',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'surface',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='釉面质感',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'transparency',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=30),
               comment=None,
               existing_comment='透明度',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'glaze_colors',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='釉色',
               existing_nullable=True)
    op.drop_index('idx_source_source_id', table_name='recipes')
    op.alter_column('redeem_codes', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='兑换码',
               existing_nullable=False)
    op.drop_index('code', table_name='redeem_codes')
    op.drop_index('idx_code', table_name='redeem_codes')
    op.create_index(op.f('ix_redeem_codes_code'), 'redeem_codes', ['code'], unique=True)
    op.create_index(op.f('ix_redeem_codes_id'), 'redeem_codes', ['id'], unique=False)
    op.create_foreign_key('fk_redeem_codes_created_by', 'redeem_codes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('redeem_logs', 'before_expiry',
               existing_type=mysql.DATETIME(),
               comment='兑换前使用期限',
               existing_nullable=True)
    op.alter_column('redeem_logs', 'after_expiry',
               existing_type=mysql.DATETIME(),
               comment='兑换后使用期限',
               existing_nullable=True)
    op.drop_index('idx_code_id', table_name='redeem_logs')
    op.drop_index('idx_user_id', table_name='redeem_logs')
    op.create_index(op.f('ix_redeem_logs_code_id'), 'redeem_logs', ['code_id'], unique=False)
    op.create_index(op.f('ix_redeem_logs_id'), 'redeem_logs', ['id'], unique=False)
    op.create_index(op.f('ix_redeem_logs_user_id'), 'redeem_logs', ['user_id'], unique=False)
    op.create_foreign_key('fk_redeem_logs_code_id', 'redeem_logs', 'redeem_codes', ['code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_redeem_logs_user_id', 'redeem_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_levels', 'max_views',
               existing_type=mysql.INTEGER(),
               comment='每日可查看配方上限，0=禁止查看',
               existing_comment='每日可查看配方上限，0=不限',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='使用期限',
               existing_nullable=False,
               existing_server_default=sa.text("'2027-07-09 00:00:00'"))
    op.drop_index('email_hash', table_name='users')
    op.drop_index('phone_hash', table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_foreign_key('fk_users_level_id', 'users', 'user_levels', ['level_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_category', table_name='work_attribute_options')
    op.create_index(op.f('ix_work_attribute_options_category'), 'work_attribute_options', ['category'], unique=False)
    op.create_index(op.f('ix_work_attribute_options_id'), 'work_attribute_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_attribute_options_id'), table_name='work_attribute_options')
    op.drop_index(op.f('ix_work_attribute_options_category'), table_name='work_attribute_options')
    op.create_index('idx_category', 'work_attribute_options', ['category'], unique=False)
    op.drop_constraint('fk_users_level_id', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index('phone_hash', 'users', ['phone_hash'], unique=True)
    op.create_index('email_hash', 'users', ['email_hash'], unique=True)
    op.alter_column('users', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='使用期限',
               existing_nullable=False,
               existing_server_default=sa.text("'2027-07-09 00:00:00'"))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.alter_column('user_levels', 'max_views',
               existing_type=mysql.INTEGER(),
               comment='每日可查看配方上限，0=不限',
               existing_comment='每日可查看配方上限，0=禁止查看',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('fk_redeem_logs_user_id', 'redeem_logs', type_='foreignkey')
    op.drop_constraint('fk_redeem_logs_code_id', 'redeem_logs', type_='foreignkey')
    op.drop_index(op.f('ix_redeem_logs_user_id'), table_name='redeem_logs')
    op.drop_index(op.f('ix_redeem_logs_id'), table_name='redeem_logs')
    op.drop_index(op.f('ix_redeem_logs_code_id'), table_name='redeem_logs')
    op.create_index('idx_user_id', 'redeem_logs', ['user_id'], unique=False)
    op.create_index('idx_code_id', 'redeem_logs', ['code_id'], unique=False)
    op.alter_column('redeem_logs', 'after_expiry',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='兑换后使用期限',
               existing_nullable=True)
    op.alter_column('redeem_logs', 'before_expiry',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='兑换前使用期限',
               existing_nullable=True)
    op.drop_constraint('fk_redeem_codes_created_by', 'redeem_codes', type_='foreignkey')
    op.drop_index(op.f('ix_redeem_codes_id'), table_name='redeem_codes')
    op.drop_index(op.f('ix_redeem_codes_code'), table_name='redeem_codes')
    op.create_index('idx_code', 'redeem_codes', ['code'], unique=False)
    op.create_index('code', 'redeem_codes', ['code'], unique=True)
    op.alter_column('redeem_codes', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='兑换码',
               existing_nullable=False)
    op.create_index('idx_source_source_id', 'recipes', ['source', 'source_id'], unique=False)
    op.alter_column('recipes', 'glaze_colors',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='釉色',
               existing_nullable=True)
    op.alter_column('recipes', 'transparency',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='透明度',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'surface',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='釉面质感',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'source_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='来源ID',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'source',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='来源',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('recipes', 'forked_from',
               existing_type=mysql.INTEGER(),
               comment='二改来源配方',
               existing_nullable=True)
    op.alter_column('recipes', 'work_count',
               existing_type=mysql.INTEGER(),
               comment='作品数量',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('recipes', 'likes',
               existing_type=mysql.INTEGER(),
               comment='点赞数',
               existing_nullable=True)
    op.alter_column('recipes', 'visibility',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='可见性',
               existing_nullable=True)
    op.alter_column('recipes', 'body_material',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='坯体料',
               existing_nullable=True)
    op.alter_column('recipes', 'kiln_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='窑炉类型',
               existing_nullable=True)
    op.alter_column('recipes', 'atmosphere',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='气氛',
               existing_nullable=True)
    op.alter_column('recipes', 'temperature',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='温度',
               existing_nullable=True)
    op.alter_column('recipes', 'category',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='分类',
               existing_nullable=True)
    op.alter_column('recipes', 'describe',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
    op.alter_column('recipes', 'images',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='图片',
               existing_nullable=True)
    op.alter_column('recipes', 'cover',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200),
               comment='封面',
               existing_nullable=True)
    op.drop_constraint('fk_recipe_versions_created_by', 'recipe_versions', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_id'), table_name='recipe_versions')
    op.create_index('idx_recipe_id', 'recipe_versions', ['recipe_id'], unique=False)
    op.alter_column('recipe_sequences', 'digits',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'3'"))
    op.drop_index(op.f('ix_recipe_seger_id'), table_name='recipe_seger')
    op.create_index('ix_recipe_seger_recipe_id', 'recipe_seger', ['recipe_id'], unique=False)
    op.drop_constraint('fk_recipe_ingredients_recipe_id', 'recipe_ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_name_hash'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.create_index('idx_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_index('idx_name_hash', 'recipe_ingredients', ['name_hash'], unique=False)
    op.alter_column('recipe_ingredients', 'is_additional',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('fk_notifications_work_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_from_user_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_user_id', 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('idx_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_user_time', 'notifications', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.create_index('idx_materials_source', 'materials', ['source'], unique=False)
    op.create_index('idx_materials_name_en', 'materials', ['name_en'], unique=False)
    op.create_index('idx_materials_name', 'materials', ['name'], unique=False)
    op.alter_column('materials', 'source',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('materials', 'name_en',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('ix_material_substitutions_id'), table_name='material_substitutions')
    op.alter_column('material_substitutions', 'note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='相似关系备注',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('material_substitutions', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='历史兼容字段，不再参与业务逻辑',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('material_substitutions', 'similarity_score',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='成分相似度 0-100',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('material_substitutions', 'target_material_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='相似材料',
               existing_nullable=False)
    op.alter_column('material_substitutions', 'source_material_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='源材料',
               existing_nullable=False)
    op.drop_index(op.f('ix_ingredient_names_id'), table_name='ingredient_names')
    op.drop_constraint('fk_firing_curves_user_id', 'firing_curves', type_='foreignkey')
    op.drop_index(op.f('ix_firing_curves_user_id'), table_name='firing_curves')
    op.create_index('idx_user_id', 'firing_curves', ['user_id'], unique=False)
    op.alter_column('firing_curves', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属用户，null=系统默认',
               existing_nullable=True)
    op.drop_constraint('fk_favorites_user_id', 'favorites', type_='foreignkey')
    op.create_table('material_oxide_backup_20260714_oxide_fill',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('formula', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('molecular_weight', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('is_analysis', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_primitive', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('sio2', mysql.FLOAT(), nullable=True),
    sa.Column('al2o3', mysql.FLOAT(), nullable=True),
    sa.Column('fe2o3', mysql.FLOAT(), nullable=True),
    sa.Column('tio2', mysql.FLOAT(), nullable=True),
    sa.Column('cao', mysql.FLOAT(), nullable=True),
    sa.Column('mgo', mysql.FLOAT(), nullable=True),
    sa.Column('na2o', mysql.FLOAT(), nullable=True),
    sa.Column('k2o', mysql.FLOAT(), nullable=True),
    sa.Column('zno', mysql.FLOAT(), nullable=True),
    sa.Column('b2o3', mysql.FLOAT(), nullable=True),
    sa.Column('p2o5', mysql.FLOAT(), nullable=True),
    sa.Column('loi', mysql.FLOAT(), nullable=True),
    sa.Column('thermal_expansion', mysql.FLOAT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('li2o', mysql.FLOAT(), nullable=True),
    sa.Column('mno2', mysql.FLOAT(), nullable=True),
    sa.Column('coo', mysql.FLOAT(), nullable=True),
    sa.Column('sno2', mysql.FLOAT(), nullable=True),
    sa.Column('cuo', mysql.FLOAT(), nullable=True),
    sa.Column('cr2o3', mysql.FLOAT(), nullable=True),
    sa.Column('pbo', mysql.FLOAT(), nullable=True),
    sa.Column('bao', mysql.FLOAT(), nullable=True),
    sa.Column('sro', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_materials_source', 'material_oxide_backup_20260714_oxide_fill', ['source'], unique=False)
    op.create_index('idx_materials_name_en', 'material_oxide_backup_20260714_oxide_fill', ['name_en'], unique=False)
    op.create_index('idx_materials_name', 'material_oxide_backup_20260714_oxide_fill', ['name'], unique=False)
    op.create_table('body_materials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'body_materials', ['name'], unique=True)
    op.create_index('ix_body_materials_id', 'body_materials', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='purchases_ibfk_3'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='purchases_ibfk_1'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='purchases_ibfk_4'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name='purchases_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_purchases_id', 'purchases', ['id'], unique=False)
    op.create_table('user_daily_views',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view_date', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='user_daily_views_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_daily_views_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_user_recipe_date', 'user_daily_views', ['user_id', 'recipe_id', 'view_date'], unique=True)
    op.create_index('idx_user_date', 'user_daily_views', ['user_id', 'view_date'], unique=False)
    op.create_table('ceramic_materials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('formula', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('molecular_weight', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('sio2', mysql.FLOAT(), nullable=True),
    sa.Column('al2o3', mysql.FLOAT(), nullable=True),
    sa.Column('fe2o3', mysql.FLOAT(), nullable=True),
    sa.Column('tio2', mysql.FLOAT(), nullable=True),
    sa.Column('cao', mysql.FLOAT(), nullable=True),
    sa.Column('mgo', mysql.FLOAT(), nullable=True),
    sa.Column('na2o', mysql.FLOAT(), nullable=True),
    sa.Column('k2o', mysql.FLOAT(), nullable=True),
    sa.Column('zno', mysql.FLOAT(), nullable=True),
    sa.Column('b2o3', mysql.FLOAT(), nullable=True),
    sa.Column('p2o5', mysql.FLOAT(), nullable=True),
    sa.Column('loi', mysql.FLOAT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ceramic_materials_name', 'ceramic_materials', ['name'], unique=False)
    op.create_index('ix_ceramic_materials_id', 'ceramic_materials', ['id'], unique=False)
    # ### end Alembic commands ###
