"""static_schema_snapshot_temp

Revision ID: af56c4dc8c47
Revises: 0010_expand_ingredient_amount
Create Date: 2026-07-15 22:06:50.573833
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af56c4dc8c47'
down_revision: Union[str, None] = '0010_expand_ingredient_amount'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_id'), 'glossary_terms', ['id'], unique=False)
    op.create_index(op.f('ix_glossary_terms_term'), 'glossary_terms', ['term'], unique=False)
    op.create_table('ingredient_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ingredient_names_id'), 'ingredient_names', ['id'], unique=False)
    op.create_table('recipe_sequences',
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('letter')
    )
    op.create_table('temperature_cones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cone_no', sa.String(length=10), nullable=False),
    sa.Column('temp_60c', sa.Integer(), nullable=True),
    sa.Column('temp_108f', sa.Integer(), nullable=True),
    sa.Column('temp_150c', sa.Integer(), nullable=True),
    sa.Column('temp_270f', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_cones_cone_no'), 'temperature_cones', ['cone_no'], unique=False)
    op.create_index(op.f('ix_temperature_cones_id'), 'temperature_cones', ['id'], unique=False)
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_free_recipes', sa.Integer(), nullable=True),
    sa.Column('max_works', sa.Integer(), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True, comment='每日可查看配方上限，0=禁止查看'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.create_table('work_attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_attribute_options_category'), 'work_attribute_options', ['category'], unique=False)
    op.create_index(op.f('ix_work_attribute_options_id'), 'work_attribute_options', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("'2027-07-09 00:00:00'"), nullable=False, comment='使用期限'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['user_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_table('firing_curves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='所属用户，null=系统默认'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('target_temp', sa.String(length=20), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firing_curves_id'), 'firing_curves', ['id'], unique=False)
    op.create_index(op.f('ix_firing_curves_user_id'), 'firing_curves', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('follower_id <> followed_id', name='ck_follow_not_self'),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('formula', sa.String(length=200), nullable=True),
    sa.Column('molecular_weight', sa.String(length=50), nullable=True),
    sa.Column('is_analysis', sa.Integer(), nullable=True),
    sa.Column('is_primitive', sa.Integer(), nullable=True),
    sa.Column('sio2', sa.Float(), nullable=True),
    sa.Column('al2o3', sa.Float(), nullable=True),
    sa.Column('fe2o3', sa.Float(), nullable=True),
    sa.Column('tio2', sa.Float(), nullable=True),
    sa.Column('cao', sa.Float(), nullable=True),
    sa.Column('mgo', sa.Float(), nullable=True),
    sa.Column('na2o', sa.Float(), nullable=True),
    sa.Column('k2o', sa.Float(), nullable=True),
    sa.Column('zno', sa.Float(), nullable=True),
    sa.Column('b2o3', sa.Float(), nullable=True),
    sa.Column('p2o5', sa.Float(), nullable=True),
    sa.Column('li2o', sa.Float(), nullable=True),
    sa.Column('mno2', sa.Float(), nullable=True),
    sa.Column('coo', sa.Float(), nullable=True),
    sa.Column('sno2', sa.Float(), nullable=True),
    sa.Column('cuo', sa.Float(), nullable=True),
    sa.Column('cr2o3', sa.Float(), nullable=True),
    sa.Column('pbo', sa.Float(), nullable=True),
    sa.Column('bao', sa.Float(), nullable=True),
    sa.Column('sro', sa.Float(), nullable=True),
    sa.Column('loi', sa.Float(), nullable=True),
    sa.Column('thermal_expansion', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_table('redeem_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='兑换码'),
    sa.Column('days', sa.Integer(), nullable=False, comment='可兑换天数'),
    sa.Column('max_uses', sa.Integer(), nullable=True, comment='最大使用次数'),
    sa.Column('current_uses', sa.Integer(), nullable=True, comment='已使用次数'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('current_uses >= 0 AND current_uses <= max_uses', name='ck_redeem_use_count'),
    sa.CheckConstraint('days > 0', name='ck_redeem_days_positive'),
    sa.CheckConstraint('max_uses > 0', name='ck_redeem_max_uses_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redeem_codes_code'), 'redeem_codes', ['code'], unique=True)
    op.create_index(op.f('ix_redeem_codes_id'), 'redeem_codes', ['id'], unique=False)
    op.create_table('user_usage_quotas',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('free_recipe_remaining', sa.Integer(), nullable=False),
    sa.Column('work_remaining', sa.Integer(), nullable=False),
    sa.Column('recipe_view_remaining', sa.Integer(), nullable=False),
    sa.Column('redeem_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_usage_quotas_quota_date'), 'user_usage_quotas', ['quota_date'], unique=False)
    op.create_table('complaint_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_replies_complaint_id'), 'complaint_replies', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_replies_id'), 'complaint_replies', ['id'], unique=False)
    op.create_table('material_substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_material_id', sa.Integer(), nullable=False, comment='源材料'),
    sa.Column('target_material_id', sa.Integer(), nullable=False, comment='相似材料'),
    sa.Column('similarity_score', sa.Float(), nullable=True, comment='成分相似度 0-100'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='历史兼容字段，不再参与业务逻辑'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='相似关系备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('similarity_score >= 0 AND similarity_score <= 100', name='ck_material_similarity_range'),
    sa.CheckConstraint('source_material_id <> target_material_id', name='ck_material_substitution_not_self'),
    sa.ForeignKeyConstraint(['source_material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_material_id', 'target_material_id', name='uq_material_substitution_pair')
    )
    op.create_index(op.f('ix_material_substitutions_id'), 'material_substitutions', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('recipe_no', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('cover', sa.String(length=200), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('temperature', sa.String(length=30), nullable=True),
    sa.Column('atmosphere', sa.String(length=20), nullable=True),
    sa.Column('kiln_type', sa.String(length=30), nullable=True),
    sa.Column('body_material', sa.String(length=30), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('work_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forked_from', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('surface', sa.String(length=30), nullable=True),
    sa.Column('transparency', sa.String(length=30), nullable=True),
    sa.Column('glaze_colors', sa.Text(), nullable=True),
    sa.Column('curve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curve_id'], ['firing_curves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_recipe_no'), 'recipes', ['recipe_no'], unique=True)
    op.create_table('redeem_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_added', sa.Integer(), nullable=False),
    sa.Column('before_expiry', sa.DateTime(timezone=True), nullable=True, comment='兑换前使用期限'),
    sa.Column('after_expiry', sa.DateTime(timezone=True), nullable=True, comment='兑换后使用期限'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('days_added > 0', name='ck_redeem_log_days_positive'),
    sa.ForeignKeyConstraint(['code_id'], ['redeem_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id', 'user_id', name='uq_redeem_log_code_user')
    )
    op.create_index(op.f('ix_redeem_logs_code_id'), 'redeem_logs', ['code_id'], unique=False)
    op.create_index(op.f('ix_redeem_logs_id'), 'redeem_logs', ['id'], unique=False)
    op.create_index(op.f('ix_redeem_logs_user_id'), 'redeem_logs', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('kiln_types', sa.Text(), nullable=True),
    sa.Column('temperatures', sa.Text(), nullable=True),
    sa.Column('firing_curve_id', sa.Integer(), nullable=True),
    sa.Column('body_material', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firing_curve_id'], ['firing_curves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_no', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('name_hash', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_additional', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_name_hash'), 'recipe_ingredients', ['name_hash'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_seger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('seger_unified', sa.String(length=500), nullable=True),
    sa.Column('seger_al2o3', sa.Float(), nullable=True),
    sa.Column('seger_sio2', sa.Float(), nullable=True),
    sa.Column('seger_ro', sa.Float(), nullable=True),
    sa.Column('acid_base_ratio', sa.Float(), nullable=True),
    sa.Column('acid_base_note', sa.String(length=500), nullable=True),
    sa.Column('seger_detail', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipe_seger_id'), 'recipe_seger', ['id'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('recipe_data', sa.Text(), nullable=False),
    sa.Column('ingredients_data', sa.Text(), nullable=False),
    sa.Column('seger_data', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('version_no > 0', name='ck_recipe_version_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'version_no', name='uq_recipe_version_no')
    )
    op.create_index(op.f('ix_recipe_versions_id'), 'recipe_versions', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_table('recipe_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_views_id'), 'recipe_views', ['id'], unique=False)
    op.create_table('to_be_fired',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_be_fired_id'), 'to_be_fired', ['id'], unique=False)
    op.create_index(op.f('ix_to_be_fired_recipe_id'), 'to_be_fired', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_to_be_fired_user_id'), 'to_be_fired', ['user_id'], unique=False)
    op.create_table('user_daily_recipe_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', 'view_date', name='uq_user_recipe_view_date')
    )
    op.create_index(op.f('ix_user_daily_recipe_views_id'), 'user_daily_recipe_views', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_recipe_views_recipe_id'), 'user_daily_recipe_views', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_user_daily_recipe_views_user_id'), 'user_daily_recipe_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_daily_recipe_views_view_date'), 'user_daily_recipe_views', ['view_date'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('atmosphere', sa.String(length=20), nullable=True),
    sa.Column('body_material', sa.String(length=30), nullable=True),
    sa.Column('kiln_type', sa.String(length=30), nullable=True),
    sa.Column('temperature', sa.String(length=30), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('glaze_colors', sa.Text(), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('transparency', sa.String(length=20), nullable=True),
    sa.Column('curve_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['curve_id'], ['firing_curves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('(recipe_id IS NULL) <> (work_id IS NULL)', name='ck_favorite_one_target'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_favorite_user_recipe'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_favorite_user_work')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('(recipe_id IS NULL) <> (work_id IS NULL)', name='ck_like_one_target'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_like_user_recipe'),
    sa.UniqueConstraint('user_id', 'work_id', name='uq_like_user_work')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('body_material', sa.String(length=30), nullable=True),
    sa.Column('kiln_type', sa.String(length=30), nullable=True),
    sa.Column('kiln_type_other', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('user_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('from_recipe_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_materials_id'), 'user_materials', ['id'], unique=False)
    op.create_table('work_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['work_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_comments_id'), 'work_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_comments_id'), table_name='work_comments')
    op.drop_table('work_comments')
    op.drop_index(op.f('ix_user_materials_id'), table_name='user_materials')
    op.drop_table('user_materials')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_user_daily_recipe_views_view_date'), table_name='user_daily_recipe_views')
    op.drop_index(op.f('ix_user_daily_recipe_views_user_id'), table_name='user_daily_recipe_views')
    op.drop_index(op.f('ix_user_daily_recipe_views_recipe_id'), table_name='user_daily_recipe_views')
    op.drop_index(op.f('ix_user_daily_recipe_views_id'), table_name='user_daily_recipe_views')
    op.drop_table('user_daily_recipe_views')
    op.drop_index(op.f('ix_to_be_fired_user_id'), table_name='to_be_fired')
    op.drop_index(op.f('ix_to_be_fired_recipe_id'), table_name='to_be_fired')
    op.drop_index(op.f('ix_to_be_fired_id'), table_name='to_be_fired')
    op.drop_table('to_be_fired')
    op.drop_index(op.f('ix_recipe_views_id'), table_name='recipe_views')
    op.drop_table('recipe_views')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_recipe_seger_id'), table_name='recipe_seger')
    op.drop_table('recipe_seger')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_name_hash'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_redeem_logs_user_id'), table_name='redeem_logs')
    op.drop_index(op.f('ix_redeem_logs_id'), table_name='redeem_logs')
    op.drop_index(op.f('ix_redeem_logs_code_id'), table_name='redeem_logs')
    op.drop_table('redeem_logs')
    op.drop_index(op.f('ix_recipes_recipe_no'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_material_substitutions_id'), table_name='material_substitutions')
    op.drop_table('material_substitutions')
    op.drop_index(op.f('ix_complaint_replies_id'), table_name='complaint_replies')
    op.drop_index(op.f('ix_complaint_replies_complaint_id'), table_name='complaint_replies')
    op.drop_table('complaint_replies')
    op.drop_index(op.f('ix_user_usage_quotas_quota_date'), table_name='user_usage_quotas')
    op.drop_table('user_usage_quotas')
    op.drop_index(op.f('ix_redeem_codes_id'), table_name='redeem_codes')
    op.drop_index(op.f('ix_redeem_codes_code'), table_name='redeem_codes')
    op.drop_table('redeem_codes')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_firing_curves_user_id'), table_name='firing_curves')
    op.drop_index(op.f('ix_firing_curves_id'), table_name='firing_curves')
    op.drop_table('firing_curves')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_work_attribute_options_id'), table_name='work_attribute_options')
    op.drop_index(op.f('ix_work_attribute_options_category'), table_name='work_attribute_options')
    op.drop_table('work_attribute_options')
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_temperature_cones_id'), table_name='temperature_cones')
    op.drop_index(op.f('ix_temperature_cones_cone_no'), table_name='temperature_cones')
    op.drop_table('temperature_cones')
    op.drop_table('recipe_sequences')
    op.drop_index(op.f('ix_ingredient_names_id'), table_name='ingredient_names')
    op.drop_table('ingredient_names')
    op.drop_index(op.f('ix_glossary_terms_term'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
